### ISSUE TITLE
e.response failure

### ISSUE THREAD

**Issue by jduss4** [CDRH/datura#161]
Looks like trying to call a method on an error that isn't working out for us.

https://github.com/CDRH/datura/blob/dev/lib/datura/file_type.rb#L69

```
Successfully transformed nela.1966_044_10.xml
Traceback (most recent call last):
    5: from /usr/local/rvm/gems/ruby-2.5.3@datura_nebraskaland/bundler/gems/datura-44f60a131bb2/lib/datura/data_manager.rb:116:in `block (3 levels) in batch_process_files'
    4: from /usr/local/rvm/gems/ruby-2.5.3@datura_nebraskaland/bundler/gems/datura-44f60a131bb2/lib/datura/data_manager.rb:284:in `transform_and_post'
    3: from /usr/local/rvm/gems/ruby-2.5.3@datura_nebraskaland/bundler/gems/datura-44f60a131bb2/lib/datura/file_type.rb:50:in `post_es'
    2: from /usr/local/rvm/gems/ruby-2.5.3@datura_nebraskaland/bundler/gems/datura-44f60a131bb2/lib/datura/file_type.rb:50:in `each'
    1: from /usr/local/rvm/gems/ruby-2.5.3@datura_nebraskaland/bundler/gems/datura-44f60a131bb2/lib/datura/file_type.rb:56:in `block in post_es'
/usr/local/rvm/gems/ruby-2.5.3@datura_nebraskaland/bundler/gems/datura-44f60a131bb2/lib/datura/file_type.rb:59:in `rescue in block in post_es': undefined method `response' for #<URI::InvalidURIError:0x0000000001af0838> (NoMethodError)
Did you mean?  respond_to?
```

**Comment by techgique** [comment]
Looks like `URI::InvalidURIError` has not methods whatsoever:
- https://github.com/ruby/uri/blob/master/lib/uri/common.rb#L164
- https://ruby-doc.org/core-2.7.0/StandardError.html

**Comment by wkdewey** [comment]
We changed how error handling works, so check if this is still relevant

**Comment by wkdewey** [comment]
I fixed this in the latest branch
